/*
 * DialogModificarTicket.java
 *
 * Created on 04-mar-2010, 16:09:00
 */
package es.typ.dialogs;

import es.typ.frames.FramePrincipal;
import es.typ.ticket.Ticket;
import es.typ.utils.Log;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author TYP - Takuya Yamaguchi Padilla
 */
public class DialogModificarTicket extends javax.swing.JDialog {

    private static SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private static SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MM-yyyy");
    private static SimpleDateFormat sdfHrs = new SimpleDateFormat("HH:mm:ss");
    private String temp = "";
    private String temp2 = "";

    /** Creates new form DialogModificarTicket */
    public DialogModificarTicket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Modificar ticket");
        setLocationRelativeTo(null);
    }

    public DialogModificarTicket(FramePrincipal framePrincipal, boolean b, DefaultComboBoxModel modelo, Ticket ticket) {
        super(framePrincipal, b);
        try {
            initComponents();
            setLocationRelativeTo(null);
            cmbTicketType.setModel(modelo);
            //lblFecha.setText(ticket.getTicketData().getDia());
            //lblHora.setText(ticket.getTicketData().getHora());
            lblFecha.setVisible(false);
            lblHora.setVisible(false);
            txtFecha.setText(ticket.getTicketData().getDia());
            txtHora.setText(ticket.getTicketData().getHora());
            temp = ticket.getTicketData().getHora();
            temp2 = sdf.format(sdf2.parse(ticket.getTicketData().getDia()));
            txtNumEntrada.setText(ticket.getTicketData().getNumeroEntradas() + "");
            cmbTicketType.setSelectedItem(ticket.getTicketData().getTicketTypeName());
            this.repaint();
        } catch (ParseException ex) {
            Logger.getLogger(DialogModificarTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    cmbTicketType = new javax.swing.JComboBox();
    txtNumEntrada = new javax.swing.JTextField();
    lblFecha = new javax.swing.JLabel();
    lblHora = new javax.swing.JLabel();
    txtFecha = new javax.swing.JTextField();
    txtHora = new javax.swing.JTextField();
    jPanel3 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setLayout(new java.awt.BorderLayout());

    jLabel1.setText("Fecha");

    jLabel2.setText("Hora");

    jLabel3.setText("Tipo ticket");

    jLabel4.setText("Numero entradas");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(54, 54, 54)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(36, 36, 36)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmbTicketType, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtNumEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(63, 63, 63)
            .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addGap(63, 63, 63)
              .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
            .addComponent(txtHora, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
        .addContainerGap(37, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(34, 34, 34)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(lblFecha)
          .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(lblHora)
          .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(cmbTicketType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(txtNumEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

    jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradas_J2SE/images/check.png"))); // NOI18N
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(152, 152, 152)
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(157, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(29, Short.MAX_VALUE))
    );

    jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ticket ticket = new Ticket();

        //sdf.format(sdf2.parse(lblFecha.getText()))
        try {
            //ticket.getTicketData().setDia(sdf.format(sdf2.parse(lblFecha.getText())));
            //ticket.getTicketData().setHora(lblHora.getText());
            try{
                ticket.getTicketData().setDia(sdf.format(sdf2.parse(txtFecha.getText())));
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "El formato de fecha no es correcto.");
                return;
            }
            try{
                sdfHrs.parse(txtHora.getText());
                ticket.getTicketData().setHora(txtHora.getText());
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "El formato de hora no es correcto.");
                return;
            }
            ticket.getTicketData().setNumeroEntradas(Integer.parseInt(txtNumEntrada.getText()));
            ticket.getTicketData().setTicketTypeName(cmbTicketType.getSelectedItem().toString());
            ticket.getTicketDAO().modificartTicket(ticket.getTicketData(), temp, temp2);
            JOptionPane.showMessageDialog(this, "El ticket se ha modifcado correctamente.");
            this.dispose();
        } catch (Exception e) {
            Log.getInstance().log(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
    
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    DialogModificarTicket dialog = new DialogModificarTicket(new javax.swing.JFrame(), true);
    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    public void windowClosing(java.awt.event.WindowEvent e) {
    System.exit(0);
    }
    });
    dialog.setVisible(true);
    }
    });
    }*/
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox cmbTicketType;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JLabel lblFecha;
  private javax.swing.JLabel lblHora;
  private javax.swing.JTextField txtFecha;
  private javax.swing.JTextField txtHora;
  private javax.swing.JTextField txtNumEntrada;
  // End of variables declaration//GEN-END:variables
}
