package es.typ.dialogs;

import es.typ.panels.PnlCrearAdmin;
import es.typ.panels.PnlCrearTicket;
import es.typ.panels.PnlCrearTipoTicket;
import es.typ.panels.PnlModificarTicket;
import es.typ.panels.PnlModificarTipoTicket;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author TYP - Takuya Yamaguchi Padilla
 */
public class DialogAdministrador extends javax.swing.JDialog {

    javax.swing.JPanel pnlCards = new javax.swing.JPanel(new CardLayout());
    CardLayout cl = (CardLayout)(pnlCards.getLayout());


    final static String CREAR_ADMINISTRADOR = "Crear administrador";
    final static String CREAR_TICKET = "Crear ticket";
    final static String MODIFICAR_TICKET = "Modificar ticket";
    final static String CREAR_TIPO_TICKET = "Crear tipo ticket";
    final static String MODIFICAR_TIPO_TICKET = "Modificar tipo ticket";

    /** Creates new form DialogAdministrador */
    public DialogAdministrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblModificarAdmin.setVisible(false);
        setLocationRelativeTo(null);
        setTitle("Gestiones administrativas");
        addComponentToPnlCards();
        pnlPrincipal.add(pnlCards, java.awt.BorderLayout.CENTER);
        //pnlPrincipal = pnlModificarTicket;
        lblModificarTicket.setForeground(Color.LIGHT_GRAY);
        pnlPrincipal.repaint();
        setVisible(true);
        setMinimumSize(new Dimension(523, 363));
    }

    private void addComponentToPnlCards(){
        //PnlCrearAdmin pnlCrearAdmin = new PnlCrearAdmin();
        //PnlModificarTicket pnlModificarTicket = new PnlModificarTicket();
        //PnlCrearTipoTicket pnlCrearTipoTicket = new PnlCrearTipoTicket();

        pnlCards.add(new PnlModificarTicket(), MODIFICAR_TICKET);
        pnlCards.add(new PnlCrearTicket(), CREAR_TICKET);
        pnlCards.add(new PnlCrearAdmin(), CREAR_ADMINISTRADOR);
        pnlCards.add(new PnlCrearTipoTicket(), CREAR_TIPO_TICKET);
        pnlCards.add(new PnlModificarTipoTicket(), MODIFICAR_TIPO_TICKET);
    }

    private void reinicioColorLabel(){
        lblModificarTicket.setForeground(new Color(45,76,121));
        lblCrearTipoTicket.setForeground(new Color(45,76,121));
        lblModificarTipoTicket.setForeground(new Color(45,76,121));
        lblCrearAdministrador.setForeground(new Color(45,76,121));
        lblCrearAdministrador.setForeground(new Color(45,76,121));
        lblCrearTicket.setForeground(new Color(45,76,121));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel3 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jPanel10 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jPanel12 = new javax.swing.JPanel();
    jPanel16 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    jPanel22 = new javax.swing.JPanel();
    jPanel23 = new javax.swing.JPanel();
    jPanel24 = new javax.swing.JPanel();
    jPanel13 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jPanel20 = new javax.swing.JPanel();
    jPanel21 = new javax.swing.JPanel();
    jPanel15 = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    jPanel17 = new javax.swing.JPanel();
    jPanel18 = new javax.swing.JPanel();
    jPanel19 = new javax.swing.JPanel();
    pnlPrincipal = new javax.swing.JPanel();
    jPanel4 = new javax.swing.JPanel();
    jPanel6 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    lblModificarTicket = new javax.swing.JLabel();
    lblCrearTicket = new javax.swing.JLabel();
    jPanel9 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    lblCrearTipoTicket = new javax.swing.JLabel();
    lblModificarTipoTicket = new javax.swing.JLabel();
    jPanel8 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    lblCrearAdministrador = new javax.swing.JLabel();
    lblModificarAdmin = new javax.swing.JLabel();
    jPanel7 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(222, 223, 227));
    jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
    jPanel1.setLayout(new java.awt.BorderLayout());

    jPanel10.setBackground(new java.awt.Color(222, 223, 227));

    javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
    jPanel10.setLayout(jPanel10Layout);
    jPanel10Layout.setHorizontalGroup(
      jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel10Layout.setVerticalGroup(
      jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 357, Short.MAX_VALUE)
    );

    jPanel1.add(jPanel10, java.awt.BorderLayout.LINE_END);

    jPanel2.setBackground(new java.awt.Color(222, 223, 227));
    jPanel2.setMinimumSize(new java.awt.Dimension(169, 55));
    jPanel2.setLayout(new java.awt.BorderLayout());

    jPanel12.setBackground(new java.awt.Color(222, 223, 227));
    jPanel12.setLayout(new java.awt.BorderLayout());

    jPanel16.setBackground(new java.awt.Color(45, 76, 121));
    jPanel16.setPreferredSize(new java.awt.Dimension(100, 122));
    jPanel16.setLayout(new java.awt.BorderLayout());

    jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    jPanel16.add(jLabel5, java.awt.BorderLayout.WEST);

    jPanel22.setBackground(new java.awt.Color(45, 76, 121));
    jPanel22.setPreferredSize(new java.awt.Dimension(100, 10));

    javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
    jPanel22.setLayout(jPanel22Layout);
    jPanel22Layout.setHorizontalGroup(
      jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel22Layout.setVerticalGroup(
      jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );

    jPanel16.add(jPanel22, java.awt.BorderLayout.NORTH);

    jPanel23.setBackground(new java.awt.Color(45, 76, 121));
    jPanel23.setPreferredSize(new java.awt.Dimension(10, 102));

    javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
    jPanel23.setLayout(jPanel23Layout);
    jPanel23Layout.setHorizontalGroup(
      jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );
    jPanel23Layout.setVerticalGroup(
      jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 102, Short.MAX_VALUE)
    );

    jPanel16.add(jPanel23, java.awt.BorderLayout.EAST);

    jPanel24.setBackground(new java.awt.Color(45, 76, 121));
    jPanel24.setPreferredSize(new java.awt.Dimension(100, 10));

    javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
    jPanel24.setLayout(jPanel24Layout);
    jPanel24Layout.setHorizontalGroup(
      jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel24Layout.setVerticalGroup(
      jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );

    jPanel16.add(jPanel24, java.awt.BorderLayout.SOUTH);

    jPanel12.add(jPanel16, java.awt.BorderLayout.EAST);

    jPanel13.setBackground(new java.awt.Color(45, 76, 121));
    jPanel13.setPreferredSize(new java.awt.Dimension(784, 80));
    jPanel13.setLayout(new java.awt.BorderLayout());

    jLabel6.setBackground(new java.awt.Color(222, 223, 227));
    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(45, 76, 121));
    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel6.setText("ticket entradas - Administrador");
    jLabel6.setToolTipText("");
    jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jLabel6.setOpaque(true);
    jPanel13.add(jLabel6, java.awt.BorderLayout.CENTER);

    jPanel20.setBackground(new java.awt.Color(45, 76, 121));
    jPanel20.setMinimumSize(new java.awt.Dimension(100, 10));
    jPanel20.setPreferredSize(new java.awt.Dimension(623, 10));

    javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
    jPanel20.setLayout(jPanel20Layout);
    jPanel20Layout.setHorizontalGroup(
      jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 436, Short.MAX_VALUE)
    );
    jPanel20Layout.setVerticalGroup(
      jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );

    jPanel13.add(jPanel20, java.awt.BorderLayout.PAGE_START);

    jPanel21.setBackground(new java.awt.Color(45, 76, 121));
    jPanel21.setMinimumSize(new java.awt.Dimension(100, 10));
    jPanel21.setPreferredSize(new java.awt.Dimension(623, 10));

    javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
    jPanel21.setLayout(jPanel21Layout);
    jPanel21Layout.setHorizontalGroup(
      jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 436, Short.MAX_VALUE)
    );
    jPanel21Layout.setVerticalGroup(
      jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );

    jPanel13.add(jPanel21, java.awt.BorderLayout.SOUTH);

    jPanel12.add(jPanel13, java.awt.BorderLayout.CENTER);

    jPanel15.setBackground(new java.awt.Color(45, 76, 121));
    jPanel15.setPreferredSize(new java.awt.Dimension(100, 122));
    jPanel15.setLayout(new java.awt.BorderLayout());

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradaJ2SE/images/icono.png"))); // NOI18N
    jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jPanel15.add(jLabel7, java.awt.BorderLayout.EAST);

    jPanel17.setBackground(new java.awt.Color(45, 76, 121));
    jPanel17.setPreferredSize(new java.awt.Dimension(100, 10));

    javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
    jPanel17.setLayout(jPanel17Layout);
    jPanel17Layout.setHorizontalGroup(
      jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel17Layout.setVerticalGroup(
      jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );

    jPanel15.add(jPanel17, java.awt.BorderLayout.NORTH);

    jPanel18.setBackground(new java.awt.Color(45, 76, 121));
    jPanel18.setPreferredSize(new java.awt.Dimension(100, 10));

    javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
    jPanel18.setLayout(jPanel18Layout);
    jPanel18Layout.setHorizontalGroup(
      jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel18Layout.setVerticalGroup(
      jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );

    jPanel15.add(jPanel18, java.awt.BorderLayout.SOUTH);

    jPanel19.setBackground(new java.awt.Color(45, 76, 121));
    jPanel19.setPreferredSize(new java.awt.Dimension(10, 102));

    javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
    jPanel19.setLayout(jPanel19Layout);
    jPanel19Layout.setHorizontalGroup(
      jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );
    jPanel19Layout.setVerticalGroup(
      jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 102, Short.MAX_VALUE)
    );

    jPanel15.add(jPanel19, java.awt.BorderLayout.LINE_START);

    jPanel12.add(jPanel15, java.awt.BorderLayout.WEST);

    jPanel2.add(jPanel12, java.awt.BorderLayout.PAGE_START);

    jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

    pnlPrincipal.setLayout(new java.awt.BorderLayout());
    jPanel1.add(pnlPrincipal, java.awt.BorderLayout.CENTER);

    jPanel4.setBackground(new java.awt.Color(222, 223, 227));
    jPanel4.setPreferredSize(new java.awt.Dimension(200, 412));
    jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

    jPanel6.setBackground(new java.awt.Color(222, 223, 227));
    jPanel6.setPreferredSize(new java.awt.Dimension(200, 100));

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(35, 38, 54));
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradaJ2SE/images/32.png"))); // NOI18N
    jLabel1.setText("Ticket");

    lblModificarTicket.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    lblModificarTicket.setForeground(new java.awt.Color(45, 76, 121));
    lblModificarTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradaJ2SE/images/lanza32.png"))); // NOI18N
    lblModificarTicket.setText("Modificar");
    lblModificarTicket.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lblModificarTicketMouseClicked(evt);
      }
    });

    lblCrearTicket.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    lblCrearTicket.setForeground(new java.awt.Color(45, 76, 121));
    lblCrearTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradaJ2SE/images/l32.png"))); // NOI18N
    lblCrearTicket.setText("Crear");
    lblCrearTicket.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lblCrearTicketMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addGap(61, 61, 61)
        .addComponent(lblCrearTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
            .addComponent(lblModificarTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
          .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblCrearTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblModificarTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(8, 8, 8))
    );

    jPanel4.add(jPanel6);

    jPanel9.setBackground(new java.awt.Color(222, 223, 227));
    jPanel9.setPreferredSize(new java.awt.Dimension(200, 150));

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(35, 38, 54));
    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradaJ2SE/images/j32.png"))); // NOI18N
    jLabel2.setText("Tipo ticket");

    lblCrearTipoTicket.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    lblCrearTipoTicket.setForeground(new java.awt.Color(45, 76, 121));
    lblCrearTipoTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradaJ2SE/images/la32.png"))); // NOI18N
    lblCrearTipoTicket.setText("Crear");
    lblCrearTipoTicket.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lblCrearTipoTicketMouseClicked(evt);
      }
    });

    lblModificarTipoTicket.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    lblModificarTipoTicket.setForeground(new java.awt.Color(45, 76, 121));
    lblModificarTipoTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradaJ2SE/images/lza32.png"))); // NOI18N
    lblModificarTipoTicket.setText("Modificar");
    lblModificarTipoTicket.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lblModificarTipoTicketMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
      jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel9Layout.createSequentialGroup()
        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel9Layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
            .addContainerGap(61, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblCrearTipoTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lblModificarTipoTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap())
    );
    jPanel9Layout.setVerticalGroup(
      jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel9Layout.createSequentialGroup()
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblCrearTipoTicket)
        .addGap(18, 18, 18)
        .addComponent(lblModificarTipoTicket)
        .addContainerGap(46, Short.MAX_VALUE))
    );

    jPanel4.add(jPanel9);

    jPanel8.setBackground(new java.awt.Color(222, 223, 227));
    jPanel8.setPreferredSize(new java.awt.Dimension(200, 100));

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(35, 38, 54));
    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradaJ2SE/images/mu32.png"))); // NOI18N
    jLabel3.setText("Administrador");

    lblCrearAdministrador.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    lblCrearAdministrador.setForeground(new java.awt.Color(45, 76, 121));
    lblCrearAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradaJ2SE/images/lza32.png"))); // NOI18N
    lblCrearAdministrador.setText("Crear");
    lblCrearAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lblCrearAdministradorMouseClicked(evt);
      }
    });

    lblModificarAdmin.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    lblModificarAdmin.setForeground(new java.awt.Color(45, 76, 121));
    lblModificarAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradaJ2SE/images/la32.png"))); // NOI18N
    lblModificarAdmin.setText("Modificar");

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
      jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel8Layout.createSequentialGroup()
        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel8Layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
            .addContainerGap(61, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblCrearAdministrador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lblModificarAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap())
    );
    jPanel8Layout.setVerticalGroup(
      jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel8Layout.createSequentialGroup()
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblCrearAdministrador)
        .addGap(18, 18, 18)
        .addComponent(lblModificarAdmin)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel4.add(jPanel8);

    jPanel7.setBackground(new java.awt.Color(222, 223, 227));

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
      jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 200, Short.MAX_VALUE)
    );
    jPanel7Layout.setVerticalGroup(
      jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 2, Short.MAX_VALUE)
    );

    jPanel4.add(jPanel7);

    jPanel5.setBackground(new java.awt.Color(222, 223, 227));

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 200, Short.MAX_VALUE)
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 2, Short.MAX_VALUE)
    );

    jPanel4.add(jPanel5);

    jPanel1.add(jPanel4, java.awt.BorderLayout.WEST);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void lblModificarTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarTicketMouseClicked
        cl.show(pnlCards, MODIFICAR_TICKET);
        reinicioColorLabel();
        lblModificarTicket.setForeground(Color.LIGHT_GRAY);
        //pnlPrincipal.add(new PnlModificarTicket(), java.awt.BorderLayout.CENTER);
        //pnlPrincipal.repaint();
    }//GEN-LAST:event_lblModificarTicketMouseClicked

    private void lblCrearAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearAdministradorMouseClicked
        cl.show(pnlCards, CREAR_ADMINISTRADOR);
        reinicioColorLabel();
        lblCrearAdministrador.setForeground(Color.LIGHT_GRAY);
        //al.add(new PnlCrearAdmin(), java.awt.BorderLayout.CENTER);
        //pnlPrincipal.repaint();
    }//GEN-LAST:event_lblCrearAdministradorMouseClicked

    private void lblCrearTipoTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearTipoTicketMouseClicked
        cl.show(pnlCards, CREAR_TIPO_TICKET);
        reinicioColorLabel();
        lblCrearTipoTicket.setForeground(Color.LIGHT_GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCrearTipoTicketMouseClicked

    private void lblModificarTipoTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarTipoTicketMouseClicked
        cl.show(pnlCards, MODIFICAR_TIPO_TICKET);
        reinicioColorLabel();
        lblModificarTipoTicket.setForeground(Color.LIGHT_GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModificarTipoTicketMouseClicked

    private void lblCrearTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearTicketMouseClicked
        cl.show(pnlCards, CREAR_TICKET);
        reinicioColorLabel();
        lblCrearTicket.setForeground(Color.LIGHT_GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCrearTicketMouseClicked

    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogAdministrador dialog = new DialogAdministrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel10;
  private javax.swing.JPanel jPanel12;
  private javax.swing.JPanel jPanel13;
  private javax.swing.JPanel jPanel15;
  private javax.swing.JPanel jPanel16;
  private javax.swing.JPanel jPanel17;
  private javax.swing.JPanel jPanel18;
  private javax.swing.JPanel jPanel19;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel20;
  private javax.swing.JPanel jPanel21;
  private javax.swing.JPanel jPanel22;
  private javax.swing.JPanel jPanel23;
  private javax.swing.JPanel jPanel24;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JLabel lblCrearAdministrador;
  private javax.swing.JLabel lblCrearTicket;
  private javax.swing.JLabel lblCrearTipoTicket;
  private javax.swing.JLabel lblModificarAdmin;
  private javax.swing.JLabel lblModificarTicket;
  private javax.swing.JLabel lblModificarTipoTicket;
  private javax.swing.JPanel pnlPrincipal;
  // End of variables declaration//GEN-END:variables

}
