/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlCrearTipoTicket.java
 *
 * Created on 10-mar-2010, 13:42:32
 */
package es.typ.panels;

import es.typ.ticket.TicketData;
import es.typ.tickettype.TicketType;
import es.typ.tickettype.TicketTypeData;
import es.typ.utils.Log;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author TYP - Takuya Yamaguchi Padilla
 */
public class PnlCrearTipoTicket extends javax.swing.JPanel {

    private TicketType ticketType = new TicketType();
    

    /** Creates new form PnlCrearTipoTicket */
    public PnlCrearTipoTicket() {
        initComponents();
        cargarComboCategoria();
        txtPrecio.setHorizontalAlignment(JTextField.RIGHT);
    }

    private void cargarComboCategoria() {

        DefaultComboBoxModel modeloCmb = ((DefaultComboBoxModel) cmbTipoTicket.getModel());
        //ArrayList datosAL = ticketType.getTicketTypeDAO().getTicketType();
        //String[] tipoTickes = new String[1];

        modeloCmb.addElement(TicketTypeData.CATEGORIA_0);
        modeloCmb.addElement(TicketTypeData.CATEGORIA_1);

        //LE PASO AL ARRAY LOS DATOS DEL ARRAYLIST
        /*for (int i = 0; i < datosAL.size(); i++) {
        tipoTickes[0] = ((TicketTypeData) datosAL.get(i)).getName();
        modeloCmb.addElement(tipoTickes[0]);
        }*/
        cmbTipoTicket.setModel(modeloCmb);
        cmbTipoTicket.repaint();

    }

    private boolean comprobarDatos() {
        txtPrecio.setBackground(Color.white);
        txtTipoTicket.setBackground(Color.white);
        if (txtTipoTicket.getText() == null || txtTipoTicket.getText().equals("")) {
            txtPrecio.setBackground(Color.red);
            return false;
        } else if (txtPrecio.getText() == null || txtPrecio.getText().equals("")) {
            try {
                Float.parseFloat(txtTipoTicket.getText());
            } catch (Exception e) {
                e.printStackTrace();
                txtTipoTicket.setBackground(Color.red);
                Log.getInstance().log(e.getMessage());
                return false;
            }
        }
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    txtTipoTicket = new javax.swing.JTextField();
    txtPrecio = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    cmbTipoTicket = new javax.swing.JComboBox();
    btnInsertar = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();

    setBackground(new java.awt.Color(222, 223, 227));

    jLabel1.setText("Nombre tipo ticket");

    jLabel2.setText("Precio");

    jLabel3.setText("Categoría");

    btnInsertar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradas_J2SE/images/check.png"))); // NOI18N
    btnInsertar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnInsertarActionPerformed(evt);
      }
    });

    jLabel4.setText("€");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(53, 53, 53)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2)
          .addComponent(jLabel1)
          .addComponent(jLabel3))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(cmbTipoTicket, 0, 143, Short.MAX_VALUE)
            .addComponent(txtTipoTicket)
            .addGroup(layout.createSequentialGroup()
              .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jLabel4))))
        .addContainerGap(114, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(txtTipoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(cmbTipoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(30, 30, 30)
        .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(34, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if (comprobarDatos()) {
            try {
                ticketType.insertTicketType(new TicketTypeData(0, txtTipoTicket.getText(), txtPrecio.getText(), cmbTipoTicket.getSelectedIndex() + ""));
                JOptionPane.showMessageDialog(this, "El tipo de ticket se ha insertado correctamente");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "No se ha podido crear el tipo de ticket");
                Log.getInstance().log(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos correctamente");
        }
    }//GEN-LAST:event_btnInsertarActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnInsertar;
  private javax.swing.JComboBox cmbTipoTicket;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField txtPrecio;
  private javax.swing.JTextField txtTipoTicket;
  // End of variables declaration//GEN-END:variables
}
