/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlModificarTipoTicket.java
 *
 * Created on 12-mar-2010, 20:27:06
 */
package es.typ.panels;

import es.typ.ticket.TicketData;
import es.typ.tickettype.TicketType;
import es.typ.tickettype.TicketTypeData;
import es.typ.utils.Log;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TYP - Takuya Yamaguchi Padilla
 */
public class PnlModificarTipoTicket extends javax.swing.JPanel {

    private TicketType ticketType = new TicketType();
    private TicketTypeData ticketTypeData;

    /** Creates new form PnlModificarTipoTicket */
    public PnlModificarTipoTicket() {
        initComponents();
        cargarTabla();
        cargarComboCategoria();
    }

    private void limpiarDatos(){
        txtPrecio.setText("");
        txtTipoTicket.setText("");
        cmbTipoTicket.setSelectedIndex(0);
        ticketTypeData = new TicketTypeData();
    }

    private void cargarTabla() {

        DefaultTableModel modelo = ((DefaultTableModel) tblTipoTicket.getModel());
        ArrayList datosAL = ticketType.getTicketTypeDAO().getTicketType();
        String[] tipoTickes = new String[4];

//LE PASO AL ARRAY LOS DATOS DEL ARRAYLIST
        for (int i = tblTipoTicket.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }

        for (int i = 0; i < datosAL.size(); i++) {
            tipoTickes[0] = ((TicketTypeData) datosAL.get(i)).getId() + "";
            tipoTickes[1] = ((TicketTypeData) datosAL.get(i)).getName();
            tipoTickes[2] = ((TicketTypeData) datosAL.get(i)).getPrice();
            if (((TicketTypeData) datosAL.get(i)).getCategory().equals("0")) {
                tipoTickes[3] = TicketTypeData.CATEGORIA_0;
            } else if (((TicketTypeData) datosAL.get(i)).getCategory().equals("1")){
                tipoTickes[3] = TicketTypeData.CATEGORIA_1;
            }
            modelo.addRow(tipoTickes);
        }

        tblTipoTicket.setModel(modelo);
        tblTipoTicket.repaint();
    }

    private void cargarComboCategoria() {

        DefaultComboBoxModel modeloCmb = ((DefaultComboBoxModel) cmbTipoTicket.getModel());
        //ArrayList datosAL = ticketType.getTicketTypeDAO().getTicketType();
        //String[] tipoTickes = new String[1];

        modeloCmb.addElement(TicketTypeData.CATEGORIA_0);
        modeloCmb.addElement(TicketTypeData.CATEGORIA_1);

        //LE PASO AL ARRAY LOS DATOS DEL ARRAYLIST
        /*for (int i = 0; i < datosAL.size(); i++) {
        tipoTickes[0] = ((TicketTypeData) datosAL.get(i)).getName();
        modeloCmb.addElement(tipoTickes[0]);
        }*/
        cmbTipoTicket.setModel(modeloCmb);
        cmbTipoTicket.repaint();

    }

    private boolean comprobarDatos() {
        txtPrecio.setBackground(Color.white);
        txtTipoTicket.setBackground(Color.white);
        if (txtTipoTicket.getText() == null || txtTipoTicket.getText().equals("")) {
            txtPrecio.setBackground(Color.red);
            return false;
        } else if (txtPrecio.getText() == null || txtPrecio.getText().equals("")) {
            try {
                Float.parseFloat(txtTipoTicket.getText());
            } catch (Exception e) {
                e.printStackTrace();
                txtTipoTicket.setBackground(Color.red);
                Log.getInstance().log(e.getMessage());
                return false;
            }
        }
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblTipoTicket = new javax.swing.JTable();
    jPanel4 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txtTipoTicket = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    txtPrecio = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    cmbTipoTicket = new javax.swing.JComboBox();
    btnModificarTipoTicket = new javax.swing.JButton();

    setLayout(new java.awt.BorderLayout());

    jPanel2.setBackground(new java.awt.Color(222, 223, 227));
    jPanel2.setLayout(new java.awt.BorderLayout());

    jPanel1.setBackground(new java.awt.Color(222, 223, 227));
    jPanel1.setLayout(new java.awt.BorderLayout());

    tblTipoTicket.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "ID", "Nombre", "Precio", "Categoría"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tblTipoTicket.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tblTipoTicketMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tblTipoTicket);
    if (tblTipoTicket.getColumnModel().getColumnCount() > 0) {
      tblTipoTicket.getColumnModel().getColumn(0).setPreferredWidth(10);
    }

    jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jPanel4.setBackground(new java.awt.Color(222, 223, 227));
    jPanel4.setPreferredSize(new java.awt.Dimension(400, 20));

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 20, Short.MAX_VALUE)
    );

    jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

    jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

    jPanel3.setBackground(new java.awt.Color(222, 223, 227));
    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos tipo ticket"));
    jPanel3.setPreferredSize(new java.awt.Dimension(451, 195));

    jLabel1.setText("Nombre tipo ticket");

    jLabel2.setText("Precio");

    txtPrecio.setEditable(false);

    jLabel3.setText("Categoría");

    cmbTipoTicket.setEnabled(false);

    btnModificarTipoTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradas_J2SE/images/floppy.png"))); // NOI18N
    btnModificarTipoTicket.setText("Modificar");
    btnModificarTipoTicket.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnModificarTipoTicketActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap(281, Short.MAX_VALUE)
        .addComponent(btnModificarTipoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
          .addGap(101, 101, 101)
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
            .addComponent(jLabel1)
            .addComponent(jLabel3))
          .addGap(18, 18, 18)
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(cmbTipoTicket, 0, 143, Short.MAX_VALUE)
            .addComponent(txtTipoTicket)
            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addContainerGap(35, Short.MAX_VALUE)))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap(140, Short.MAX_VALUE)
        .addComponent(btnModificarTipoTicket))
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
          .addGap(7, 7, 7)
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel1)
            .addComponent(txtTipoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(18, 18, 18)
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel2)
            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(18, 18, 18)
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel3)
            .addComponent(cmbTipoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addContainerGap(62, Short.MAX_VALUE)))
    );

    jPanel2.add(jPanel3, java.awt.BorderLayout.NORTH);

    add(jPanel2, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

    private void tblTipoTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTipoTicketMouseClicked
        try {
            /*ticketType = new TicketType();
            ticketType.getTicketTypeData().setName(tblTipoTicket.getValueAt(tblTipoTicket.getSelectedRow(), 0) + "");
            ticketType.getTicketTypeData().setPrice(tblTipoTicket.getValueAt(tblTipoTicket.getSelectedRow(), 1) + "");
            ticketType.getTicketTypeData().setCategory(tblTipoTicket.getValueAt(tblTipoTicket.getSelectedRow(), 2) + "");*/

            // se obtiene el objeto seleccionado
            ticketTypeData = new TicketTypeData();
            ticketTypeData.setId(Integer.parseInt(tblTipoTicket.getValueAt(tblTipoTicket.getSelectedRow(), 0) + ""));
            //ticketTypeData.setName(tblTipoTicket.getValueAt(tblTipoTicket.getSelectedRow(), 1) + "");
            //ticketTypeData.setPrice(tblTipoTicket.getValueAt(tblTipoTicket.getSelectedRow(), 2) + "");
            //ticketTypeData.setCategory(tblTipoTicket.getValueAt(tblTipoTicket.getSelectedRow(), 3) + "");

            // se muestran los datos en el panel de datos
            txtTipoTicket.setText(tblTipoTicket.getValueAt(tblTipoTicket.getSelectedRow(), 1) + "");
            txtPrecio.setText(tblTipoTicket.getValueAt(tblTipoTicket.getSelectedRow(), 2) + "");
            if(tblTipoTicket.getValueAt(tblTipoTicket.getSelectedRow(), 3).equals(TicketTypeData.CATEGORIA_0)){
                cmbTipoTicket.setSelectedIndex(0);
            } else if(tblTipoTicket.getValueAt(tblTipoTicket.getSelectedRow(), 3).equals(TicketTypeData.CATEGORIA_1)){
                cmbTipoTicket.setSelectedIndex(1);
            }
            /*String fecha = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            String hora = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
            String tipoTicket = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
            String numEntrada = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();*/
            //new DialogModificarTicket(framePrincipal, true, modeloCmb, ticket).setVisible(true);
            //cargarTickets(fechaInicio, fechaFin, tipoTicket);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            Log.getInstance().log(e.getMessage());
        }
    }//GEN-LAST:event_tblTipoTicketMouseClicked

    private void btnModificarTipoTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarTipoTicketActionPerformed
        if (comprobarDatos()) {
            ticketTypeData.setName(txtTipoTicket.getText());
            ticketTypeData.setPrice(txtPrecio.getText());
            ticketTypeData.setCategory(cmbTipoTicket.getSelectedIndex() + "");
            try {
                ticketType.updateTicketType(ticketTypeData);
                JOptionPane.showMessageDialog(this, "El tipo de ticket se ha modificado correctamente");
                cargarTabla();
                limpiarDatos();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "No se ha podido modificar el tipo de ticket");
                Log.getInstance().log(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos correctamente");
        }
    }//GEN-LAST:event_btnModificarTipoTicketActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnModificarTipoTicket;
  private javax.swing.JComboBox cmbTipoTicket;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblTipoTicket;
  private javax.swing.JTextField txtPrecio;
  private javax.swing.JTextField txtTipoTicket;
  // End of variables declaration//GEN-END:variables
}
