/*
 * Principal.java
 *
 * Created on 27-feb-2010, 23:28:52
 */
package es.typ.frames;

import es.typ.dialogs.DialogAdminLogin;
import es.typ.dialogs.DialogBusquedaModificarTicket;
import es.typ.dialogs.DialogInformes;
//import es.TicketEntradas_J2SE.print.Impresora;
import es.typ.print.ImprimirArqueo;
import es.typ.print.ImprimirTicket;
import es.typ.print.PrintTicket;
import es.typ.ticket.Ticket;
import es.typ.ticket.TicketData;
import es.typ.tickettype.TicketType;
import es.typ.tickettype.TicketTypeData;
import es.typ.utils.Log;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Takuya
 */
public class FramePrincipal extends javax.swing.JFrame {

    private TicketType ticketType = new TicketType();
    private Ticket ticket = new Ticket();
    private PrintTicket impresora;// = new Impresora_2();

    /** Creates new form Principal */
    public FramePrincipal() {
        //UIManager.put("nimbusBase", new Color(...));
//UIManager.put("nimbusBlueGrey", new Color(...));
//UIManager.put("control", new Color(...));
        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
            Log.getInstance().log(e.getMessage());
        }

        initComponents();
        setSize(800, 600);
        setLocationRelativeTo(null);
        setTitle("Gestion de entradas");
        cargarTipoTickets();
        setVisible(true);
        setIconImage((new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradas_J2SE/images/icono.png"))).getImage());
        //Button2.setVisible(false);
    }

    private void cargarTipoTickets() {
        /*DefaultTableModel  modelo = new DefaultTableModel();
        ArrayList datosAL = ticketType.getTicketTypeDAO().getTicketType();
        for (int i = 0; i < datosAL.size(); i++) {
        Object[] dat = {((TicketTypeData)datosAL.get(i)).getName()};
        modelo.addRow(dat);

        }
        jTable1.setModel(modelo);
        jTable1.repaint();*/
        Thread t = new Thread() {

            @Override
            public void run() {
                DefaultTableModel modelo = ((DefaultTableModel) jTable1.getModel());
                ArrayList datosAL = ticketType.getTicketTypeDAO().getTicketType();
                String[] tipoTickes = new String[1];//ARRAY DE 4

                //LE PASO AL ARRAY LOS DATOS DEL ARRAYLIST
                for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                    modelo.removeRow(i);
                }

                for (int i = 0; i < datosAL.size(); i++) {
                    tipoTickes[0] = ((TicketTypeData) datosAL.get(i)).getName();
                    modelo.addRow(tipoTickes);
                }
                jTable1.setModel(modelo);
                jTable1.repaint();
            }
        };
        t.start();

    }

    private boolean isDatosCorrectos() {
        // Se conprueba que se ha seleccionado una fila de la tabla
        if (!jTable1.getRowSelectionAllowed()) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado el tipo de ticket.");
            return false;
            // Se comprueba que se ha insertado un texto
        } else if (jTextField1.getText() == null || jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No se ha insertado el número de ticket's.");
            return false;
        }
        //En el caso de que no sea un entero
        try {
            Integer.parseInt(jTextField1.getText());
        } catch (Exception e) {
            Log.getInstance().log(e.getMessage());
            JOptionPane.showMessageDialog(this, "No se ha insertado un número váilido de ticket's.");
            return false;
        }
        return true;
    }

    private void limpiarDatos() {
        cargarTipoTickets();
        jTextField1.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel10 = new javax.swing.JPanel();
    jPanel9 = new javax.swing.JPanel();
    jButton5 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jPanel16 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jPanel22 = new javax.swing.JPanel();
    jPanel23 = new javax.swing.JPanel();
    jPanel24 = new javax.swing.JPanel();
    jPanel6 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jPanel20 = new javax.swing.JPanel();
    jPanel21 = new javax.swing.JPanel();
    jPanel15 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jPanel17 = new javax.swing.JPanel();
    jPanel18 = new javax.swing.JPanel();
    jPanel19 = new javax.swing.JPanel();
    jPanel4 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jPanel5 = new javax.swing.JPanel();
    jPanel12 = new javax.swing.JPanel();
    jPanel13 = new javax.swing.JPanel();
    jPanel14 = new javax.swing.JPanel();
    btnInsertarTicket = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jPanel7 = new javax.swing.JPanel();
    jPanel8 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jPanel11 = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Gestión de ticket");
    setMinimumSize(new java.awt.Dimension(800, 600));

    jPanel1.setBackground(new java.awt.Color(222, 223, 227));
    jPanel1.setLayout(new java.awt.BorderLayout());

    jPanel10.setBackground(new java.awt.Color(222, 223, 227));

    javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
    jPanel10.setLayout(jPanel10Layout);
    jPanel10Layout.setHorizontalGroup(
      jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel10Layout.setVerticalGroup(
      jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 388, Short.MAX_VALUE)
    );

    jPanel1.add(jPanel10, java.awt.BorderLayout.LINE_START);

    jPanel9.setBackground(new java.awt.Color(222, 223, 227));
    jPanel9.setPreferredSize(new java.awt.Dimension(175, 264));

    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradasJ2SE/images/personal.png"))); // NOI18N
    jButton5.setText("Administración");
    jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton5ActionPerformed(evt);
      }
    });

    jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradasJ2SE/images/print_printer.png"))); // NOI18N
    jButton4.setText("Arquero diario");
    jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradasJ2SE/images/kwrite.png"))); // NOI18N
    jButton3.setText("Informes");
    jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jButton3.setMaximumSize(new java.awt.Dimension(101, 25));
    jButton3.setMinimumSize(new java.awt.Dimension(101, 23));
    jButton3.setPreferredSize(new java.awt.Dimension(101, 25));
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
      jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel9Layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
          .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
          .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, Short.MAX_VALUE))
        .addGap(81, 81, 81))
    );
    jPanel9Layout.setVerticalGroup(
      jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel9Layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(198, Short.MAX_VALUE))
    );

    jPanel1.add(jPanel9, java.awt.BorderLayout.LINE_END);

    jPanel2.setBackground(new java.awt.Color(222, 223, 227));
    jPanel2.setPreferredSize(new java.awt.Dimension(840, 20));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 840, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 20, Short.MAX_VALUE)
    );

    jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

    jPanel3.setBackground(new java.awt.Color(222, 223, 227));
    jPanel3.setLayout(new java.awt.BorderLayout());

    jPanel16.setBackground(new java.awt.Color(45, 76, 121));
    jPanel16.setPreferredSize(new java.awt.Dimension(100, 122));
    jPanel16.setLayout(new java.awt.BorderLayout());

    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradasJ2SE/images/icono.png"))); // NOI18N
    jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    jPanel16.add(jLabel4, java.awt.BorderLayout.WEST);

    jPanel22.setBackground(new java.awt.Color(45, 76, 121));
    jPanel22.setPreferredSize(new java.awt.Dimension(100, 10));

    javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
    jPanel22.setLayout(jPanel22Layout);
    jPanel22Layout.setHorizontalGroup(
      jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel22Layout.setVerticalGroup(
      jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );

    jPanel16.add(jPanel22, java.awt.BorderLayout.NORTH);

    jPanel23.setBackground(new java.awt.Color(45, 76, 121));
    jPanel23.setPreferredSize(new java.awt.Dimension(10, 102));

    javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
    jPanel23.setLayout(jPanel23Layout);
    jPanel23Layout.setHorizontalGroup(
      jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );
    jPanel23Layout.setVerticalGroup(
      jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 102, Short.MAX_VALUE)
    );

    jPanel16.add(jPanel23, java.awt.BorderLayout.EAST);

    jPanel24.setBackground(new java.awt.Color(45, 76, 121));
    jPanel24.setPreferredSize(new java.awt.Dimension(100, 10));

    javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
    jPanel24.setLayout(jPanel24Layout);
    jPanel24Layout.setHorizontalGroup(
      jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel24Layout.setVerticalGroup(
      jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );

    jPanel16.add(jPanel24, java.awt.BorderLayout.SOUTH);

    jPanel3.add(jPanel16, java.awt.BorderLayout.EAST);

    jPanel6.setBackground(new java.awt.Color(45, 76, 121));
    jPanel6.setPreferredSize(new java.awt.Dimension(784, 80));
    jPanel6.setLayout(new java.awt.BorderLayout());

    jLabel2.setBackground(new java.awt.Color(222, 223, 227));
    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(45, 76, 121));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Gestión de entradas");
    jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jLabel2.setOpaque(true);
    jPanel6.add(jLabel2, java.awt.BorderLayout.CENTER);

    jPanel20.setBackground(new java.awt.Color(45, 76, 121));
    jPanel20.setMinimumSize(new java.awt.Dimension(100, 10));
    jPanel20.setPreferredSize(new java.awt.Dimension(623, 10));

    javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
    jPanel20.setLayout(jPanel20Layout);
    jPanel20Layout.setHorizontalGroup(
      jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 640, Short.MAX_VALUE)
    );
    jPanel20Layout.setVerticalGroup(
      jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );

    jPanel6.add(jPanel20, java.awt.BorderLayout.PAGE_START);

    jPanel21.setBackground(new java.awt.Color(45, 76, 121));
    jPanel21.setMinimumSize(new java.awt.Dimension(100, 10));
    jPanel21.setPreferredSize(new java.awt.Dimension(623, 10));

    javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
    jPanel21.setLayout(jPanel21Layout);
    jPanel21Layout.setHorizontalGroup(
      jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 640, Short.MAX_VALUE)
    );
    jPanel21Layout.setVerticalGroup(
      jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );

    jPanel6.add(jPanel21, java.awt.BorderLayout.SOUTH);

    jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

    jPanel15.setBackground(new java.awt.Color(45, 76, 121));
    jPanel15.setPreferredSize(new java.awt.Dimension(100, 122));
    jPanel15.setLayout(new java.awt.BorderLayout());

    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradasJ2SE/images/icono.png"))); // NOI18N
    jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jPanel15.add(jLabel3, java.awt.BorderLayout.EAST);

    jPanel17.setBackground(new java.awt.Color(45, 76, 121));
    jPanel17.setPreferredSize(new java.awt.Dimension(100, 10));

    javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
    jPanel17.setLayout(jPanel17Layout);
    jPanel17Layout.setHorizontalGroup(
      jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel17Layout.setVerticalGroup(
      jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );

    jPanel15.add(jPanel17, java.awt.BorderLayout.NORTH);

    jPanel18.setBackground(new java.awt.Color(45, 76, 121));
    jPanel18.setPreferredSize(new java.awt.Dimension(100, 10));

    javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
    jPanel18.setLayout(jPanel18Layout);
    jPanel18Layout.setHorizontalGroup(
      jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel18Layout.setVerticalGroup(
      jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );

    jPanel15.add(jPanel18, java.awt.BorderLayout.SOUTH);

    jPanel19.setBackground(new java.awt.Color(45, 76, 121));
    jPanel19.setPreferredSize(new java.awt.Dimension(10, 102));

    javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
    jPanel19.setLayout(jPanel19Layout);
    jPanel19Layout.setHorizontalGroup(
      jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 10, Short.MAX_VALUE)
    );
    jPanel19Layout.setVerticalGroup(
      jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 102, Short.MAX_VALUE)
    );

    jPanel15.add(jPanel19, java.awt.BorderLayout.LINE_START);

    jPanel3.add(jPanel15, java.awt.BorderLayout.WEST);

    jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

    jPanel4.setBackground(new java.awt.Color(222, 223, 227));
    jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(45, 76, 121), null));
    jPanel4.setLayout(new java.awt.BorderLayout());

    jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Tipo de ticket"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jTable1.setRowHeight(24);
    jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane1.setViewportView(jTable1);

    jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jPanel5.setBackground(new java.awt.Color(222, 223, 227));
    jPanel5.setLayout(new java.awt.BorderLayout());

    jPanel12.setBackground(new java.awt.Color(222, 223, 227));
    jPanel12.setPreferredSize(new java.awt.Dimension(130, 30));

    javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
    jPanel12.setLayout(jPanel12Layout);
    jPanel12Layout.setHorizontalGroup(
      jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 130, Short.MAX_VALUE)
    );
    jPanel12Layout.setVerticalGroup(
      jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 128, Short.MAX_VALUE)
    );

    jPanel5.add(jPanel12, java.awt.BorderLayout.LINE_END);

    jPanel13.setBackground(new java.awt.Color(222, 223, 227));
    jPanel13.setPreferredSize(new java.awt.Dimension(130, 30));

    javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
    jPanel13.setLayout(jPanel13Layout);
    jPanel13Layout.setHorizontalGroup(
      jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 130, Short.MAX_VALUE)
    );
    jPanel13Layout.setVerticalGroup(
      jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 128, Short.MAX_VALUE)
    );

    jPanel5.add(jPanel13, java.awt.BorderLayout.LINE_START);

    jPanel14.setBackground(new java.awt.Color(222, 223, 227));

    btnInsertarTicket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    btnInsertarTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradasJ2SE/images/print.png"))); // NOI18N
    btnInsertarTicket.setText("Imprimir");
    btnInsertarTicket.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnInsertarTicketActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel1.setText("Número de entradas:");

    jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
    jPanel14.setLayout(jPanel14Layout);
    jPanel14Layout.setHorizontalGroup(
      jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel14Layout.createSequentialGroup()
        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel14Layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(btnInsertarTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel14Layout.setVerticalGroup(
      jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel14Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnInsertarTicket)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel5.add(jPanel14, java.awt.BorderLayout.CENTER);

    jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_END);

    jPanel7.setBackground(new java.awt.Color(222, 223, 227));
    jPanel7.setPreferredSize(new java.awt.Dimension(20, 162));

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
      jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 20, Short.MAX_VALUE)
    );
    jPanel7Layout.setVerticalGroup(
      jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 236, Short.MAX_VALUE)
    );

    jPanel4.add(jPanel7, java.awt.BorderLayout.LINE_START);

    jPanel8.setBackground(new java.awt.Color(222, 223, 227));
    jPanel8.setAlignmentX(0.0F);
    jPanel8.setPreferredSize(new java.awt.Dimension(50, 162));

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/TicketEntradasJ2SE/images/refresh.png"))); // NOI18N
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
      jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(37, 37, 37))
    );
    jPanel8Layout.setVerticalGroup(
      jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel8Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButton1)
        .addContainerGap(180, Short.MAX_VALUE))
    );

    jPanel4.add(jPanel8, java.awt.BorderLayout.LINE_END);

    jPanel11.setBackground(new java.awt.Color(222, 223, 227));
    jPanel11.setPreferredSize(new java.awt.Dimension(578, 20));

    javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
    jPanel11.setLayout(jPanel11Layout);
    jPanel11Layout.setHorizontalGroup(
      jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 561, Short.MAX_VALUE)
    );
    jPanel11Layout.setVerticalGroup(
      jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 20, Short.MAX_VALUE)
    );

    jPanel4.add(jPanel11, java.awt.BorderLayout.PAGE_START);

    jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarTicketActionPerformed
        if (isDatosCorrectos()) {
            try {
                Thread t = new Thread() {
                    @Override
                    public void run() {
                        //Se obtiene la fila seleccionada
                        Object name = jTable1.getValueAt(jTable1.getSelectedRow(), jTable1.getSelectedColumn());
                        //int idType = ticketType.getTicketTypeDAO().getIdTicketType(name.toString());
                        //Se obtiene el id del tipo de ticket y el precio
                        TicketTypeData ticketTypeData = ticketType.getTicketTypeDAO().getIdAndPriceFromTicketType(name.toString().toUpperCase());
                        TicketData ticketData = new TicketData(Integer.parseInt(jTextField1.getText()), ticketTypeData.getId());
                        ticket.insertTicket(ticketData);
                        // esto es una chapu deberia de insetar en ticketData un objeto TicketTypeData
                        ticketData.setPrecio(ticketTypeData.getPrice());
                        ticketData.setTicketTypeName(name.toString());
                        //ArrayList al = new ArrayList();
                        //al.add(ticketData);
                        //impresora = new PrintTicket();
                        //impresora.imprimirTicket(ticketData);
                        if(!ticketTypeData.getPrice().equals("0")){
                            ImprimirTicket imp = new ImprimirTicket(ticketData);
                        }
                        //JOptionPane.showMessageDialog(this, "El ticket se ha generado correctamente.");
                        limpiarDatos();
                    }
                };
                t.start();
            } catch (Exception e) {
                Log.getInstance().log(e.getMessage());
            }
        }

    }//GEN-LAST:event_btnInsertarTicketActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new DialogInformes(this, false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ArrayList ttAL = ticketType.getTicketTypeDAO().getTicketTypeOrderByCategory();
        ArrayList arqueo = ticket.getTicketDAO().getArqueoDiarioTickets();
        ArrayList result = new ArrayList();
        Object temp = new Object();
        boolean existe = false;
        for (int i = 0; i < ttAL.size(); i++) {
            existe = false;
            for (int j = 0; j < arqueo.size(); j++) {
                temp = arqueo.get(j);
                if (((TicketTypeData) ttAL.get(i)).getName().equals(((TicketData) arqueo.get(j)).getTicketTypeName())) {
                    result.add(arqueo.get(j));
                    existe = true;
                }
            }
            if (!existe) {
                result.add(new TicketData(0, "", ((TicketTypeData) ttAL.get(i)).getName(), ((TicketTypeData) ttAL.get(i)).getPrice(), ((TicketTypeData) ttAL.get(i)).getCategory(), ((TicketData) temp).getTotalNumeroEntradas(), ((TicketData) temp).getTotalTotal()));
            }
        }
        //muy chapu
        TicketData tdAnterior = (TicketData)result.get(0);
        TicketData tdActual;
        int numeroEntradasGratis = 0;
        for(int i = 0; i < result.size(); i++){
            tdActual = (TicketData)result.get(i);
            if(tdActual.getCategoria().equals("0")){
                tdActual.setTotalTotalInt(0);
                tdActual.setTotalTotal("0");
                numeroEntradasGratis += ((TicketData)result.get(i)).getNumeroEntradas();
                tdActual.setTotalNumeroEntradas(numeroEntradasGratis);
                tdAnterior = tdActual;
            } else {
                tdActual.setTotalNumeroEntradas(tdActual.getTotalNumeroEntradas() - numeroEntradasGratis);
                //((TicketData)result.get(i)).setTotalTotalInt(tdActual.getTotalTotalInt() - tdAnterior.getTotalTotalInt());
                //((TicketData)result.get(i)).setTotalTotal(((TicketData)result.get(i)).getTotalTotalInt() + "");
            }
        }
        //result.add(new TicketData(0, "", ((TicketTypeData) ttAL.get(ttAL.size())).getName(), ((TicketTypeData) ttAL.get(ttAL.size())).getPrice(), ((TicketTypeData) ttAL.get(ttAL.size())).getCategory(), ((TicketData) temp).getTotalNumeroEntradas(), ((TicketData) temp).getTotalTotal()));
        ImprimirArqueo ia = new ImprimirArqueo(result);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new DialogAdminLogin(this, false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargarTipoTickets();
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
    
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new Principal().setVisible(true);
    }
    });
    }*/
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnInsertarTicket;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel10;
  private javax.swing.JPanel jPanel11;
  private javax.swing.JPanel jPanel12;
  private javax.swing.JPanel jPanel13;
  private javax.swing.JPanel jPanel14;
  private javax.swing.JPanel jPanel15;
  private javax.swing.JPanel jPanel16;
  private javax.swing.JPanel jPanel17;
  private javax.swing.JPanel jPanel18;
  private javax.swing.JPanel jPanel19;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel20;
  private javax.swing.JPanel jPanel21;
  private javax.swing.JPanel jPanel22;
  private javax.swing.JPanel jPanel23;
  private javax.swing.JPanel jPanel24;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables
}
